# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{makebelieve}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristopher Kosmatka"]
  s.date = %q{2009-12-17}
  s.description = %q{
      A framework and tool set for building Bayesian Networks.  Included are
      a quasi domain specific language for network specification as well as
      several algorithms for performing inference queries and parameter
      learning.
    }
  s.email = %q{kjkosmatka@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/makebelieve.rb",
     "lib/makebelieve/elimination.rb",
     "lib/makebelieve/gibbs_inference.rb",
     "lib/makebelieve/graph.rb",
     "lib/makebelieve/monkey_patches.rb",
     "lib/makebelieve/network.rb",
     "lib/makebelieve/potential.rb",
     "lib/makebelieve/variable.rb",
     "makebelieve.gemspec",
     "spec/features.rb",
     "test/helper.rb",
     "test/test_bioinformatics.rb",
     "test/test_biotwo.rb",
     "test/test_elimination.rb",
     "test/test_gibbs_inference.rb",
     "test/test_graph.rb",
     "test/test_inference.rb",
     "test/test_monkey_patches.rb",
     "test/test_network.rb",
     "test/test_potential.rb",
     "test/test_potential_multiplication.rb",
     "test/test_variable.rb"
  ]
  s.homepage = %q{http://github.com/kjkosmatka/makebelieve}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A toolbox for building Bayes Nets}
  s.test_files = [
    "spec/features.rb",
     "test/helper.rb",
     "test/test_bioinformatics.rb",
     "test/test_biotwo.rb",
     "test/test_elimination.rb",
     "test/test_gibbs_inference.rb",
     "test/test_graph.rb",
     "test/test_inference.rb",
     "test/test_monkey_patches.rb",
     "test/test_network.rb",
     "test/test_potential.rb",
     "test/test_potential_multiplication.rb",
     "test/test_variable.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

